name: checks

on: 
  push:
    tags: 
      - v*
    branches:
      - master
      - vs-code-task

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set up Environment  # always: replace package name
      id: prep
      run: |
        pip install -q pipenv build
        pipenv install -d
        echo "::set-output name=package::mendeley_watchdog"
    - name: Flake8
      if: ${{ startsWith( github.ref, 'refs/heads/' ) }}
      id: flake8
      run : pipenv run flake8 --doctests --max-doc-length 72 ${{ steps.prep.outputs.package }}
    - name: Pylint
      if: ${{ startsWith( github.ref, 'refs/heads/' ) }}
      id: pylint
      run: pipenv run pylint -f colorized ${{ steps.prep.outputs.package }} || pipenv run pylint-exit -efail -wfail $?
    - name: Build  # on windows: replace var assignment and dist path 
      id: build
      run: |
        pipenv run pipenv --rm
        pip uninstall pipenv
        name=$(python setup.py --name)
        version=$(python setup.py --version)
        sdist=./dist/${name}-${version}.tar.gz
        echo "::set-output name=name::${name}"
        echo "::set-output name=sdist::${sdist}"
        python -m build --sdist --wheel --outdir dist/
    - name: Deploy
      id: deploy
      run: python -m pip install ${{ steps.build.outputs.sdist }}
    - name: Release
      if: ${{ startsWith( github.ref, 'refs/tags/v' ) }}
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ steps.build.outputs.name }} ${{ github.ref }}
    - name: Upload
      if: ${{ startsWith( github.ref, 'refs/tags/v' ) }}
      id: upload
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ${{ steps.build.outputs.sdist }}
        asset_name: ${{ steps.build.outputs.name }}.tar.gz
        asset_content_type: application/gzip
